export const LINKS = {
  login_api: '/login',
  logout_api: '/logout',
  register_api: '/users',
  check_email_exist: '/users/checkEmail',
  check_username_exist: '/users/checkUserName',
  check_phone_number__exist: '/users/checkPhoneNumber',
  active_register: '/users/activeUser',
  reset_password: '/users/resetPassword',
  forget_pass: '/users/resetPasswordRequest',
  profile: '/users/profile',
  change_password: '/users/profile/changePassword',
  listPackage: '/subscriptions/list',
  detailPackage: '/subscriptions',
  order_user: '/orders/user',
  order: '/orders',
  order_silent: '/orders/silent',
  order_email: '/orders/email',
  order_email_admin: '/orders/emailAdmin',
  order_email_report: '/orders/emailReport',
  payment: '/payment',
  payment_cancel: '/payment/cancel',
  payment_create: '/payment/create-payment',
  licenses_create: '/licenses/create',
  licenses_user: '/licenses/user',
  licenses_can_used: '/licenses/canUsed',
  licenses_activate_next: '/licenses/activate-next',
}
